spring:
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
redisson:
  config: |
    singleServerConfig:
      address: "redis://${SPRING_REDIS_HOST:localhost}:${SPRING_REDIS_PORT:6379}"
      connectionPoolSize: 10
      connectionMinimumIdleSize: 2
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500

ticketing:
  lock:
    wait-time-seconds:5
    lease-time-seconds:10